---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: required
dist: trusty

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

script:
  # Basic role syntax check
  - cd tests; ./run_tests.sh
  - dpkg -l | grep luftpost
  - file /etc/lustpost/luftpost.conf

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

